# -*- coding: utf-8 -*-
"""imageTOText.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acYDnY-QXwySxDNrzbMmEKzDLLcwl0IH
"""

# Step 1: Install necessary packages including Tesseract OCR
# !apt-get update
# !apt-get install -y tesseract-ocr
# !pip install pytesseract pillow

# Step 2: Import necessary libraries
from PIL import Image
import pytesseract
from google.colab import files

# Step 3: Upload the image file
uploaded = files.upload()

# Step 4: Extract text from the uploaded image
def image_to_text(image_path):
    # Open the image file
    img = Image.open(image_path)

    # Use pytesseract to do OCR on the image
    text = pytesseract.image_to_string(img)

    return text

# Get the uploaded file name
image_path = list(uploaded.keys())[0]  # This will get the first uploaded file

# Step 5: Extract text from the uploaded image
extracted_text = image_to_text(image_path)
print("Extracted Text:\n", extracted_text)