# -*- coding: utf-8 -*-
"""pdfData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172IDdWYMKZJaH954u4ctJpGIvOugyCAO
"""

# Install required libraries
!pip install PyPDF2 pdfplumber tabula-py

# Upload PDF file
from google.colab import files
uploaded = files.upload()

# Get the uploaded file name
file_name = list(uploaded.keys())[0]

# 1. Extract text using PyPDF2
import PyPDF2

def extract_text_pypdf2(file_name):
    print("Extracting text using PyPDF2...\n")
    with open(file_name, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page_num in range(len(reader.pages)):
            page = reader.pages[page_num]
            text = page.extract_text()
            print(f"Page {page_num+1}:\n{text}\n")

extract_text_pypdf2(file_name)

# 2. Extract text using pdfplumber (for better structured text or tables)
import pdfplumber

def extract_text_pdfplumber(file_name):
    print("Extracting text using pdfplumber...\n")
    with pdfplumber.open(file_name) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            print(text)

extract_text_pdfplumber(file_name)

# 3. Extract tables using tabula-py
import tabula

def extract_tables_tabula(file_name):
    print("Extracting tables using tabula-py...\n")
    tables = tabula.read_pdf(file_name, pages='all', multiple_tables=True)
    for i, table in enumerate(tables):
        print(f"Table {i+1}:")
        print(table)

extract_tables_tabula(file_name)